# Generated by Django 5.1.5 on 2025-02-13 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_movies', to='server.movie'),
        ),
        migrations.AddField(
            model_name='cart',
            name='movie_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
