# Generated by Django 5.1.5 on 2025-02-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_cart_movie_cart_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='movie',
        ),
        migrations.AddField(
            model_name='cart',
            name='movie_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='movie_title',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
