# Generated by Django 5.1.5 on 2025-02-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='price',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(default=0),
        ),
    ]
