# Generated by Django 5.1.5 on 2025-02-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_movie_price_movie_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster_path',
            new_name='image',
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
