# Generated by Django 5.1.5 on 2025-02-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_rename_poster_path_movie_image_movie_backdrop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
