# Generated by Django 5.1.5 on 2025-02-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_order_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='movie',
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='movie_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='movie_title',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
