# Generated by Django 5.1.5 on 2025-02-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_remove_order_movie_order_image_order_movie_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.IntegerField(),
        ),
    ]
